name: gateway
namespace: default

replicaCount: 1

image:
  repository: ghcr.io/askaryankarine/bmstu-ds-5/gateway
  tag: "latest"

postgres:
  dsn: ""

app:
  port: 80
  env: "prod"
  jwk_url: http://helpme.ds-labs.tw1.ru/realms/rsoi/protocol/openid-connect/certs

gateway:
  reservation: "http://194.87.86.112/default/reservation/api/v1"
  loyalty: "http://194.87.86.112/default/loyalty/api/v1"
  payment: "http://194.87.86.112/default/payment/api/v1"