name: service
namespace: default

replicaCount: 1

image:
  repository: ghcr.io/askaryankarine/bmstu-ds-5
  tag: "latest"

postgres:
  dsn: ""

app:
  port: 80
  env: "prod"

gateway:
  reservation: ""
  loyalty: ""
  payment: ""