name: Build Service
on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
    secrets:
      REGISTRY_TOKEN:
        required: true

jobs:
  build:
    name: Build and Push Docker image to Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - id: repository
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository }}

      - name: Login to GitHub Container Registry
        run: docker login ghcr.io -u ${{ github.actor }} --password ${{ secrets.REGISTRY_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ steps.repository.outputs.lowercase }}/${{ inputs.service-name }}:${{ github.sha }} -f ./deployments/${{ inputs.service-name }}/Dockerfile .      

      - name: Push Docker image to GitHub Container Registry
        run: |
          docker push ghcr.io/${{ steps.repository.outputs.lowercase }}/${{ inputs.service-name }}:${{ github.sha }}