name: GitHub Classroom Workflow
on:
  push:
    branches: [ master ]
jobs:
  test-gateway:
    name: Test Gateway Service
    uses: ./.github/workflows/test.yml
    with:
      service-name: gateway

  test-loyalty:
    name: Test Loyalty Service
    uses: ./.github/workflows/test.yml
    with:
      service-name: loyalty

  test-payment:
    name: Test Payment Service
    uses: ./.github/workflows/test.yml
    with:
      service-name: payment

  test-reservation:
    name: Test Reservation Service
    uses: ./.github/workflows/test.yml
    with:
      service-name: reservation

  build-gateway:
    name: Build Gateway Service
    needs: [ "test-gateway" ]
    uses: ./.github/workflows/build.yml
    with:
      service-name: gateway
    secrets:
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}

  build-loyalty:
    name: Build Loyalty Service
    needs: [ "test-loyalty" ]
    uses: ./.github/workflows/build.yml
    with:
      service-name: loyalty
    secrets:
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}

  build-payment:
    name: Build Payment Service
    needs: [ "test-payment" ]
    uses: ./.github/workflows/build.yml
    with:
      service-name: payment
    secrets:
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}

  build-reservation:
    name: Build Reservation Service
    needs: [ "test-reservation" ]
    uses: ./.github/workflows/build.yml
    with:
      service-name: reservation
    secrets:
      REGISTRY_TOKEN: ${{ secrets.REGISTRY_TOKEN }}

  deploy-loyalty:
    name: Deploy Loyalty Service
    needs: [ "build-loyalty" ]
    uses: ./.github/workflows/deploy.yml
    with:
      service-name: loyalty
    secrets:
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
      PGDSN: ${{ secrets.LOYALTY_DSN }}

  deploy-payment:
    name: Deploy Payment Service
    needs: [ "build-payment" ]
    uses: ./.github/workflows/deploy.yml
    with:
      service-name: payment
    secrets:
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
      PGDSN: ${{ secrets.PAYMENT_PG }}

  deploy-reservation:
    name: Deploy Reservation Service
    needs: [ "build-reservation" ]
    uses: ./.github/workflows/deploy.yml
    with:
      service-name: reservation
    secrets:
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
      PGDSN: ${{ secrets.RESERVATION_PG }}

  deploy-gateway:
    name: Deploy Gateway Service
    needs: [ "build-gateway" ]
    uses: ./.github/workflows/deploy.yml
    with:
      service-name: gateway
    secrets:
      KUBECONFIG: ${{ secrets.KUBECONFIG }}
      PGDSN: ""

  api_test:
    name: Autograding
    needs: [ "deploy-gateway", "deploy-loyalty", "deploy-payment", "deploy-reservation" ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v2/postman/collection.json
          environment: v2/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true