name: Deploy service
on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string
    secrets:
      PGDSN:
        required: true
      KUBECONFIG:
        required: true

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: azure/k8s-set-context@v1
        name: Set K8s context
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBECONFIG }}

      - uses: azure/setup-kubectl@v4
        name: Setup kubectl

      - uses: azure/setup-helm@v4.2.0
        name: Setup helm

      - name: Helm chart install
        run: >
          helm upgrade --install --create-namespace -n default
          --set 'image.tag=${{ github.sha }}'
          --set 'postgres.dsn=${{ secrets.PGDSN }}'
          --dependency-update
          -f  deployments/${{ inputs.service-name }}/values.yaml
          ${{ inputs.service-name }} helm
